#define CONSTANT_Debug_ShowEventsCount 1
#define CONSTANT_Debug_ShowInteractions 1
#define CONSTANT_Camera_Zoomout 1
#define CONSTANT_Camera_ZoomoutValue 10.000000f
#define CONSTANT_Profiler_Memory 0
#define CONSTANT_Profiler_Cpu 0
#define CONSTANT_Profiler_CpuSpansList 0
#define CONSTANT_Profiler_Pause 0
#define CONSTANT_Renderer_WithSoftware 0
#define CONSTANT_Renderer_DifferentResolution 0
#define CONSTANT_Renderer_ResolutionWidth 960.f
#define CONSTANT_Renderer_ResolutionHeight 540.f
